### ISSUE TITLE
Sticking on coordinates

### ISSUE THREAD

**Issue by readelev** [Alb-310/Geogramint#11]
Hi, this is a great tool! Thanks for putting it out there. I've had this issue a few times where the application seems to stick with a previous set of coordinates, even when I reset and sometimes even after closing the program and restarting. This could be an issue on my end with something else I'm running on my computer. Any ideas?

**Comment by Alb-310** [comment]
Hello, this issue is related to Telegram's API. If you make many API calls or change your location too many times in short period, Telegram’s API may detect this and return the same results as your last scan. In this case, it’s best to wait for 10-15 minutes before trying again. ( cf. [Wiki](https://github.com/Alb-310/Geogramint/wiki/FAQ#sometime-when-i-run-a-scan-in-geogramint-i-get-the-same-results-as-my-last-scan-while-being-in-a-complete-different-location-why) )

**Comment by readelev** [comment]
Okay thanks
